# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCheckUpdates < Formula
  desc "go-check-updates upgrades your go.mod dependencies to the latest versions, ignoring specified versions."
  homepage "https://github.com/fogfish/go-check-updates"
  version "0.1.0"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fogfish/go-check-updates/releases/download/v0.1.0/go-check-updates_0.1.0_darwin_amd64"
      sha256 "a0cf843920c1956e2939e48846b1e34610f79d34b24a78d8becf39663e472382"

      def install
        bin.install "go-check-updates_0.1.0_darwin_amd64" => "go-check-updates"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fogfish/go-check-updates/releases/download/v0.1.0/go-check-updates_0.1.0_darwin_arm64"
      sha256 "7da66f8df0a597211704d82d795fb47373242a7a2640694cb5addb972eda3e40"

      def install
        bin.install "go-check-updates_0.1.0_darwin_arm64" => "go-check-updates"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fogfish/go-check-updates/releases/download/v0.1.0/go-check-updates_0.1.0_linux_amd64"
      sha256 "1043fedd116a267ccbfbdcd5d4355aadcb09905b9be92fe80db62b9528b6de5d"

      def install
        bin.install "go-check-updates_0.1.0_linux_amd64" => "go-check-updates"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fogfish/go-check-updates/releases/download/v0.1.0/go-check-updates_0.1.0_linux_arm64"
      sha256 "4f8f8b1db811aee537a6003cb08b42723ecd6c6221cd88247b425a54bbe2b03e"

      def install
        bin.install "go-check-updates_0.1.0_linux_arm64" => "go-check-updates"
      end
    end
  end

  test do
    system "#{bin}/go-check-updates -v"
  end
end
