# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCheckUpdates < Formula
  desc "go-check-updates upgrades your go.mod dependencies to the latest versions, ignoring specified versions."
  homepage "https://github.com/fogfish/go-check-updates"
  version "0.4.2"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fogfish/go-check-updates/releases/download/v0.4.2/go-check-updates_0.4.2_darwin_amd64"
      sha256 "b6a94618b96414b3ac7e960e1de6b8db3d764a59a38e9405e850ffbc1482cf65"

      def install
        bin.install "go-check-updates_0.4.2_darwin_amd64" => "go-check-updates"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fogfish/go-check-updates/releases/download/v0.4.2/go-check-updates_0.4.2_darwin_arm64"
      sha256 "080f9f9abed99401d67bc03b118da5d5885e04e0aee4b1b28d0dab14ca4b654b"

      def install
        bin.install "go-check-updates_0.4.2_darwin_arm64" => "go-check-updates"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fogfish/go-check-updates/releases/download/v0.4.2/go-check-updates_0.4.2_linux_arm64"
      sha256 "01268da54a85d88a7d491e48de9e5aff78d56545b081994e93aabc4d66ee577c"

      def install
        bin.install "go-check-updates_0.4.2_linux_arm64" => "go-check-updates"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fogfish/go-check-updates/releases/download/v0.4.2/go-check-updates_0.4.2_linux_amd64"
      sha256 "49901d9488b155a3920a3b112c929937384b122a9d34bf7499426886012d004b"

      def install
        bin.install "go-check-updates_0.4.2_linux_amd64" => "go-check-updates"
      end
    end
  end

  test do
    system "#{bin}/go-check-updates -v"
  end
end
