# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCheckUpdates < Formula
  desc "go-check-updates upgrades your go.mod dependencies to the latest versions, ignoring specified versions."
  homepage "https://github.com/fogfish/go-check-updates"
  version "0.4.5"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fogfish/go-check-updates/releases/download/v0.4.5/go-check-updates_0.4.5_darwin_amd64"
      sha256 "c596e2847c87c69ffefd4b4035c97d6850311c3cb6ffd647cd05ddde8f5c0204"

      def install
        bin.install "go-check-updates_0.4.5_darwin_amd64" => "go-check-updates"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fogfish/go-check-updates/releases/download/v0.4.5/go-check-updates_0.4.5_darwin_arm64"
      sha256 "e70283d7eb7a55439863bbc5a40fcca48189d82e4e64aea0711164a4b1f84717"

      def install
        bin.install "go-check-updates_0.4.5_darwin_arm64" => "go-check-updates"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fogfish/go-check-updates/releases/download/v0.4.5/go-check-updates_0.4.5_linux_amd64"
      sha256 "cbb4835b1e30b86cd4d1c5b339849a8e7cd374a987bdf2ce220decbf8916162a"

      def install
        bin.install "go-check-updates_0.4.5_linux_amd64" => "go-check-updates"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fogfish/go-check-updates/releases/download/v0.4.5/go-check-updates_0.4.5_linux_arm64"
      sha256 "d36c47dee737ddd726e2500753bf01729a3c181d566d4b845514c2cfc21825bf"

      def install
        bin.install "go-check-updates_0.4.5_linux_arm64" => "go-check-updates"
      end
    end
  end

  test do
    system "#{bin}/go-check-updates -v"
  end
end
